<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>True</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="R3" Version="1.2.9" />
  </ItemGroup>

</Project>
