<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Application Base">
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
		<PlatformTarget>x64</PlatformTarget>		
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>

		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>
		
	<PropertyGroup Label="Application">
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<DebugType>embedded</DebugType>
		<ApplicationIcon>Infrastructure\Resources\SSHF-S16-32-SS-36-128-Max256-512.ico</ApplicationIcon>
		
		<Version>0.8.7</Version>		
		<Product>Screenshot Helper by FarmV</Product>
		<Description>Screenshot Helper by FarmV</Description>
		<Copyright>https://github.com/FarmV/SSHF</Copyright>
	</PropertyGroup>
	
	<PropertyGroup Label="IDE Settings">		
		<RootNamespace>FVH.SSHF</RootNamespace>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NoWarn>$(NoWarn);IDE0200</NoWarn>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />
			
	<ItemGroup Label="Nuget Dependencies">
		<PackageReference Include="MahApps.Metro" Version="2.4.10" />
		<PackageReference Include="MahApps.Metro.IconPacks" Version="5.1.0" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.1" />
		<PackageReference Include="R3" Version="1.2.9" />
		<PackageReference Include="R3Extensions.WPF" Version="1.2.9" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.162">
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
		
	<ItemGroup Label="Other Dependencies">
	  <ProjectReference Include="..\BackgroundCallbackSharp\BackgroundCallbackSharp.csproj" />
	</ItemGroup>
	
	<ItemGroup Label="Included ressources">
		<Resource Include="Infrastructure\Resources\SSHF-S16-32-SS-36-128-Max256-512.ico">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>	
	</ItemGroup>
	
</Project>
